### ISSUE TITLE
[JOSS Review] Suggested revisions on code quality

### ISSUE THREAD

**Issue by matthewfeickert** [palaimon/ipyannotator#38]
For suggested revisions for https://github.com/openjournals/joss-reviews/issues/4480:

In the code there are multiple instances of things like

```python
from nbdev import *
```

```console
$ git grep 'import \*'
dev_notes.md:from nbdev.export import *
nbs/00d_doc_utils.ipynb:    "from nbdev import *"
nbs/01_bbox_canvas.ipynb:    "from nbdev import *"
nbs/01_helpers.ipynb:    "from nbdev import *\n",
nbs/01a_datasets.ipynb:    "from nbdev import *"
nbs/01b_dataset_video.ipynb:    "from nbdev import *"
nbs/01b_tutorial_image_classification.ipynb:    "from nbdev import *"
nbs/01c_tutorial_bbox.ipynb:    "from nbdev import *"
nbs/01d_tutorial_video_annotator.ipynb:    "from nbdev import *"
nbs/02_navi_widget.ipynb:    "from nbdev import *\n",
nbs/02a_right_menu_widget.ipynb:    "from nbdev import *"
nbs/02b_grid_menu.ipynb:    "from nbdev import *"
nbs/03_storage.ipynb:    "from nbdev import *\n",
nbs/04_bbox_annotator.ipynb:    "from nbdev import *"
nbs/05_image_button.ipynb:    "from nbdev import *"
nbs/06_capture_annotator.ipynb:    "from nbdev import *"
nbs/07_im2im_annotator.ipynb:    "from nbdev import *"
nbs/13_datasets_legacy.ipynb:    "from nbdev import *\n",
nbs/15_coordinates_input.ipynb:    "from nbdev import *"
nbs/16_custom_buttons.ipynb:    "from nbdev import *"
nbs/18_bbox_trajectory.ipynb:    "from nbdev import *\n",
nbs/19_bbox_video_annotator.ipynb:    "from nbdev import *"
scripts/check_lint.sh:# F403 -> 'from module import *' used; unable to detect undefined names
scripts/check_lint.sh:# Cause : "from nbdev import *"
```

The use of `import *` should be avoided at all costs in Python code unless there is an extremely good reason to use it. For anything close to a library I do not think there are any.

**Comment by itepifanio** [comment]
Hi @matthewfeickert.

We are not a big fan of the `import *` heavily used and advocated by nbdev [0, 1] (even though we like many of the unconventional ideas used in nbdev).
Given that nbdev was designed explicitly to work with `import *` and using explicit imports with this library is not very convenient we decided to use a compromise.

- the dev notebooks use the `import *`, but only for nbdev modules
- our library doesn't use any `import *`, so our users don't have to face any of the potential downsides of `import *`.

As you can see from your grep these imports are located on the notebooks only and are not exported to the final library (located in the ipyannotator folder).
Strictly speaking, our library doesn't use any `import *`, can you live with the compromise we explained above?

If not how would you suggest to proceed?

[0] Their [boilerplate code](https://nbdev1.fast.ai/example.html#Edit-index.ipynb) already comes with the `import *` for example.
[1] hn discussion with nbdev core dev https://news.ycombinator.com/item?id=24386147

**Comment by matthewfeickert** [comment]
> As you can see from your grep these imports are located on the notebooks only and are not exported to the final library (located in the ipyannotator folder).
> Strictly speaking, our library doesn't use any `import *`, can you live with the compromise we explained above?

That's valid! I appreciate the compromise that you've already made in your approaches. :+1: 

> If not how would you suggest to proceed?

Sorry, I didn't make this clear enough, but you don't need to address this at all to proceed with the review. This is just a suggestion that I am making as someone who has poked around you code during the review, but it is not at all something that is keeping you from moving forward with publication. :+1:
