### ISSUE TITLE
Add support for multiple bbox per image

### ISSUE THREAD

**Issue by ibayer** [palaimon/ipyannotator#6]
Motivation
----------

ipyannotator currently support single object annotation with bounding boxes (bbox). However often a image contains more then one object of interest that should be annotated.

Develop and Integrate Multi BBox Widget
---------------------------------------

Suggested steps:

- explore `01c_tutorial_bbox.ipynb` to see the current bbox implementation in action
- extend `01_bbox_canvas.ipynb` with a new class `MultiBBoxCanvas` which supports displaying and drawing of multiple bboxs
- duplicate `04_bbox_annotator.ipynb` as `04b_multi_bbox_annotator.ipynb` and replace the `BBoxCanvas` with `MultiBBoxCanvas`

**Comment by itepifanio** [comment]
@ibayer I think we can close this issue now

**Comment by ibayer** [comment]
@itepifanio 
Indeed, thanks to your contributions to our 0.5.2 release. :)
